### ISSUE TITLE
DeepPartial and assigning empty object.

### ISSUE THREAD

**Issue by tregusti** [ts-essentials/ts-essentials#178] opened 2020-09-21 08:45 UTC
I'm using `DeepPartial` with a generic type. And it prevents me from assigning `{}` to it.

```ts
import { DeepPartial } from 'ts-essentials'

const notAllowedToAssignDefaultValue = <
    TReduxRootState extends Record<string, any> = Record<string, unknown>
>(initialState: TReduxRootState) => (state: DeepPartial<TReduxRootState> = {}) => {
  // ... 
}

const worksWithEmptyObjectAssignment = <
    TReduxRootState extends Record<string, any> = Record<string, unknown>
>(initialState: TReduxRootState) => (state: DeepPartial<Record<string, unknown>> = {}) => {
  // ...
}
```

Play in [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEQKarABQIa2NgGzgF84AzKCEOAchgGcBaVe+1AOxnwPpoCg+AYwjt68dhBgBBAgQgB3VABMAKhCmtgAc3Zoy2AK4EYANUIHUcALxwAPHziO4KgErKDADxcRJAZRjYMJaoHkHsSvRwbsJQSrZiUMDsWgA0cNjsAJ4AfNZRqDFxCUmpcAbsANYS8uzZfNkAFEnAXIT+gagAXM5uSp7efgFBAJTWuQ1iHd1oGDh4hLau7l4+MO1BuTYIxKNWuQgOcAD0R3AAdBdwfMQCwqLw8tAV9ADqLQAWAKLgMJkA8gAjABWBWkmh0IA48Bs9icPWWAzWQ2CoQ4EXyhXiMESyTSGRyeWi0CK2JKaXKVQUtXqTXYLW46y68L6K0GHV240mQWm6CwuFaBFsRNiWJxpQp1Vqm0QOzGiEOJ3OF2uQA)

The only difference is that I moved the default value in the generic definition to the explicitly specify the incoming parameter type.

What am I doing wrong? How can I type this genericly and keep the extends from an object? Or is this a bug somewhere?

**Comment by tregusti** [comment] 2020-09-21 18:58
Is this a dupe or just related to #123?

**Comment by bbarry** [comment] 2020-09-24 22:51
I think it is the same issue (or very close)?

As a workaround you can use:

```typescript
const notAllowedToAssignDefaultValue = <
    TReduxRootState extends Record<string, any> = Record<string, unknown>
>(initialState: TReduxRootState) => (state: Partial<TReduxRootState> | DeepPartial<TReduxRootState> = {}) => {
  // ... 
}
```

The problem can be simplified to 

```typescript
export type Test<T> = T extends number // doesn't really matter what the condition is
  ? Partial<T>
  : Partial<T>; 

function conditionalPartialTestErrors<T>(){
  return (state: Test<T> = {}) => {
  }
}
function conditionalPartialTestCompiles<T>(){
  return (state: Partial<T> | Test<T> = {}) => {
  }
}
```

Partial doesn't seem to work inside conditions?

**Comment by tregusti** [comment] 2020-10-01 13:11
Your suggestion works for now @bbarry, but I don't know it it's enough to close this as fixed. It's not pretty to have to do it like that. But close as dupe if it's close enough.

**Comment by bbarry** [comment] 2020-10-01 13:32
Searching for issues on microsoft/TypeScript I found this: https://github.com/microsoft/TypeScript/issues/37524

**Comment by ajitjha393** [comment] 2022-11-07 11:24
@Beraliv @tregusti 
I think it should work if we remove `Distribution` from the equation maybe it will **"resolve"** sooner?
```ts
type Test<T> = [T] extends number? Partial<T> : Partial<T>
function conditionalPartialTestErrors<T>(){
  return (state: Test<T> = {}) => {
  }
}
function conditionalPartialTestCompiles<T>(){
  return (state: Partial<T> | Test<T> = {}) => {
  }
}

```

Because then TS can resolve it directly and not at the point of instantiation.

**Comment by Beraliv** [comment] 2022-11-28 09:48
> ```ts
> DeepPartial
> ```

I think it will limit us in what can be used in `DeepPartial` and won't allow to resolve unions or will make it more complicated.

Let's extra-check it in the library if that's possible at all. I would be interested to resolve it

**Comment by Beraliv** [comment] 2024-04-27 22:49
Marking as a duplicate of https://github.com/ts-essentials/ts-essentials/issues/123 and closing this issue.

**Closed by Beraliv** 2024-04-27 22:49 UTC
Labels: bug
