### ISSUE TITLE
Enhancement: [DeepPartial] Add an optional parameter to exclude/ignore certain types

### ISSUE THREAD

**Issue by charmpitz** [ts-essentials/ts-essentials#379] opened 2023-11-10 17:39 UTC
### What

I propose the following pattern that can be used to exclude ValueObject pattern or objects that have constructors.
```
DeepPartial<T, ExcludedTypes>
```

### Examples

```
class Duration {
    constructor(public readonly value: number) {}
}
type ValueObject = Timestamp | Duration | Moment;

type SomeType = {
     value: number;
     duration: Duration;
}

type Test = DeepPartial<SomeType, ValueObject>;
/*
Expected
{
     value?: number;
     duration?: Duration;
}
instead of
{
     value?: number;
     duration?: {
          value?: number
     };
}
*/
```

**Comment by Beraliv** [comment] 2023-11-20 13:51
Hey @charmpitz!

Thank you for your feature request, I believe it's a duplicate of https://github.com/ts-essentials/ts-essentials/issues/361. Let me know if this is a different one and I will re-open it again

**Closed by Beraliv** 2023-11-20 13:50 UTC
Labels: enhancement
